#!/bin/zsh

HISTFILE=~/.zsh_histfile
HISTSIZE=2000
SAVEHIST=2000

####################
# environment vars
####################
export EDITOR=`which vim`
export VISUAL=`which gvim`
export SVN_EDITOR=`which vim`
export PAGER=`which less`
export MANPAGER=`which less`
export RSYNC_RSH=`which ssh`
export MEDIAPLAYER=`which kaffeine`
export MUSICPLAYER=`which amarok`
export BROWSER=`which firefox`
export PDFVIEWER=`which kpdf`
export IMAGEVIEWER=`which showimg`
export OFFICEVIEWER=`which ooffice`
export LC_ALL='de_DE.UTF-8'
export LANG='de_DE.UTF-8'
export LC_CTYPE=C
export PGPPATH=~/.crypt/.gnupg

# special dirs
export TODO=/mnt/nfs/todo
export MEDIA=/mnt/nfs/media
export HTDOCS=/mnt/nfs/htdocs
export FTPDIR=/mnt/nfs/ftp
export DATA=/mnt/nfs/data
export USBSTICK=/mnt/usbstick
export SDCARD=/mnt/sd
export DVDRW=/mnt/dvdrw

####################
# optionen
####################
export LESS='-S'

