#!/bin/zsh

# SET
setopt autocd 
setopt autolist 
setopt automenu 
setopt autopushd 
setopt braceccl 
setopt cdablevars
setopt correct 
setopt extendedglob 
setopt noflowcontrol
setopt histignoredups 
setopt histignorespace 
setopt histnostore 
setopt listtypes 
setopt longlistjobs
setopt cshnullglob 
setopt magicequalsubst 
setopt listpacked
setopt pushdtohome 
setopt rcexpandparam 
setopt rcquotes
setopt sunkeyboardhack 
setopt zle 
setopt nobadpattern 
setopt autoremoveslash
setopt completeinword 
setopt autoparamkeys

# UNSET
unsetopt bgnice 
unsetopt norcs 
unsetopt notify 
unsetopt nonomatch 
unsetopt hashdirs 
unsetopt listambiguous
